name: Debug
run-name: Debug
on: [push]
env:
  SECRET_JWT: ${{secrets.orgFeeder.SECRET_JWT}}
  EMAIL: ${{secrets.EMAIL}}
  PASSWORD: ${{secrets.PASSWORD}}
  MONGO_URI: ${{secrets.MONGO_URI}}
  MONGO_TEST_URI: ${{secrets.MONGO_TEST_URI}}
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo "SECRET_JWT: $SECRET_JWT"
          echo "EMAIL: $EMAIL"
          echo "PASSWORD: $PASSWORD"
          echo "MONGO_URI: $MONGO_URI"
          echo "MONGO_TEST_URI: $MONGO_TEST_URI"
