name: orgFeeder
run-name: ${{github.actor}} is running Github Actions...
on: [pull_request, push]
jobs:
  run-jest:
    runs-on: ubuntu-latest
    environment: orgFeeder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - name: run tests
        run: npm test
        env:
          SECRET_JWT: ${{secrets.SECRET_JWT}}
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_TEST_URI: ${{secrets.MONGO_TEST_URI}}
