name: orgFeeder
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: orgFeeder
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        env:
          SECRET_JWT: ${{secrets.SECRET_JWT}}
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_TEST_URI: ${{secrets.MONGO_TEST_URI}}
